# ===== STAGE 1: build/publish =====
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src

ARG BUILD_CONFIGURATION=Release

COPY src/Worker/UsersWorker.csproj src/Worker/
COPY src/api/users-svc.csproj src/api/
RUN dotnet restore src/Worker/UsersWorker.csproj

COPY src/ src/
RUN dotnet publish src/Worker/UsersWorker.csproj -c $BUILD_CONFIGURATION -o /app /p:UseAppHost=false

# ===== STAGE 2: runtime =====
# O worker referencia o projeto Web (`users-svc`), então precisa do shared framework `Microsoft.AspNetCore.App`.
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS final
WORKDIR /app

# Instalar certificados e timezone
RUN apk add --no-cache icu-libs tzdata

COPY --from=build --chown=app:app /app .

ENV DOTNET_EnableDiagnostics=false
ENV DOTNET_TieredPGO=1
ENV DOTNET_TC_QuickJitForLoops=1
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

USER app

ENTRYPOINT ["dotnet", "UsersWorker.dll"]

